### ISSUE TITLE
if(readWord(APP1_START + (i*4)) == -1) should be if(readWord(APP1_START + (i*4)) == 0x00)

### ISSUE THREAD

**Issue by FlashForger** [viktorvano/STM32-Bootloader#1]

**Comment by viktorvano** [comment]
No. An empty erased cell has a 32-bit hexadecimal value 0xFFFF which is equal to -1.
And I have demonstrated that in the video from 6:48 to 8:50.   https://youtu.be/S0s69xNE1dE?t=408
https://www.rapidtables.com/convert/number/hex-to-decimal.html  and check a value of FFFF as a signed decimal number.

**Comment by FlashForger** [comment]
1) Function "readWord" returns uint32_t, so at least compare it with 0xFFFF. I mean, it's a bit wrong to compare uint with signed integer, it's a potential for mistake.

2) The way your custom flasher "erases" memory is opposite to what the STM32 ST-LINK Utility does, cause it fills the memory with zeroes when you click on "Full chip erase".

**Comment by viktorvano** [comment]
1. Yes, I wanted to keep it as 0xFFFF when I was writing the code, but also wondered if it is going to compare as a signed integer anyway.

2. I am using a normal function to erase the memory. HAL_FLASHEx_Erase(&EraseInitStruct, &PageError);
When you actually check the "STM32 ST-LINK Utility" it shows table full of 0xFFFF. It was erased via "STM32 ST-LINK Utility".

![STM32 utility](https://user-images.githubusercontent.com/25414104/104340545-16bce480-54f9-11eb-9473-05035dbf57e9.png)

**Comment by FlashForger** [comment]
Just out of curiosity checked how the flash memory of a completely brand new untouched "first connection" flash memory looks like - mine is filled with zeroes. The difference might be - I am on STM32L0 right now, maybe "empy memory" here means "filled with zeroes". 

![image](https://user-images.githubusercontent.com/5873562/104341189-cd20c980-54f9-11eb-9b6d-2fab9af5b227.png)

**Comment by FlashForger** [comment]
That's eraser in stm32l0xx_hal_flash_ex.c

void FLASH_PageErase(uint32_t PageAddress)
{
  /* Clean the error context */
  pFlash.ErrorCode = HAL_FLASH_ERROR_NONE;

  /* Set the ERASE bit */
  SET_BIT(FLASH->PECR, FLASH_PECR_ERASE);

  /* Set PROG bit */
  SET_BIT(FLASH->PECR, FLASH_PECR_PROG);

  /* Write 00000000h to the first word of the program page to erase */
  *(__IO uint32_t *)(uint32_t)(PageAddress & ~(FLASH_PAGE_SIZE - 1)) = 0x00000000;
}

**Comment by viktorvano** [comment]
In "stm32f1xx_hal_flash_ex.c" it is quite different.

Do you know that you are comparing code of L0xx with F1xx?

void FLASH_PageErase(uint32_t PageAddress)
{
  /* Clean the error context */
  pFlash.ErrorCode = HAL_FLASH_ERROR_NONE;

#if defined(FLASH_BANK2_END)
  if(PageAddress > FLASH_BANK1_END)
  { 
    /* Proceed to erase the page */
    SET_BIT(FLASH->CR2, FLASH_CR2_PER);
    WRITE_REG(FLASH->AR2, PageAddress);
    SET_BIT(FLASH->CR2, FLASH_CR2_STRT);
  }
  else
  {
#endif /* FLASH_BANK2_END */
    /* Proceed to erase the page */
    SET_BIT(FLASH->CR, FLASH_CR_PER);
    WRITE_REG(FLASH->AR, PageAddress);
    SET_BIT(FLASH->CR, FLASH_CR_STRT);
#if defined(FLASH_BANK2_END)
  }
#endif /* FLASH_BANK2_END */
}

And this definition
#define WRITE_REG(REG, VAL)   ((REG) = (VAL))

**Comment by FlashForger** [comment]
Yep, I know.

Ok, that's a confusion. I can't find exact documentation on this, namely what "empty" means by one or another chip, but I think that's worth mentioning as a comment in the code. Better yet - have a #ifdef directive for different series, that is, if there is a documentation on this

**Comment by viktorvano** [comment]
I wrote a small note in ReadMe: "To find out what is your's MCU Page Size, read a Reference Manual".
But in the video I said that several things may differ among different types or families of MCUs.
