### ISSUE TITLE
DOUBLEWORD Program Write

### ISSUE THREAD

**Issue by folny** [viktorvano/STM32-Bootloader#4]
Hi

I would like to ask what changes should be made in your codes so that the bootloader can be used for other cpu tips that support 64bit flash writing FLASH_TYPEPROGRAM_DOUBLEWORD.

**Comment by viktorvano** [comment]
Hi,
Also STM32F1 series support flashing a double word (64bit).

It is a bit of a challenge.

You would need to modify the body this function:
static int8_t CDC_Receive_FS(uint8_t* Buf, uint32_t *Len)

Where you would need to change 4 to 8 in the condition and use 64 bit integer + more binary rotations.
Currently this is for 32 bit:
if(length == 4 && flashStatus == Unlocked)
	{
		uint32_t dataToFlash = (Buf[3]<<24) +
							  (Buf[2]<<16) +
							  (Buf[1]<<8) +
							  Buf[0];//32bit Word contains 4 Bytes
		flashWord(dataToFlash);
	}

Then in "void flashWord(uint32_t dataToFlash)" you will need to change the offset increment from 4 to 8.
Flashed_offset += 4;//to 8
also: status = HAL_FLASH_Program(FLASH_TYPEPROGRAM_WORD, address, dataToFlash); to:
status = HAL_FLASH_Program(FLASH_TYPEPROGRAM_DOUBLEWORD, address, dataToFlash);

And maybe in other places, if it contains something related to 4 byte (32bit) flashing.

In the Java app you will need to change it too, not to read 4 bytes, but 8 bytes and send them.
And if there will be the last 32-bit word in the bin file (50% chance), you will need to add there remaining 4 bytes to make a 64-bit double-word and send it to STM32.
Depending on the STM family, you need to check if the empty memory cells are set to 0xFFFF or 0x0000 and fill the last 32bit word with those.

Cheers :)

**Comment by folny** [comment]
Thank you for your answer but it seems that it does not work with the application for java I can not send a string that has 64bit even though I set it like this.

  if(readChars < fileSize)
            {
                byte[] word = new byte[8];
                for(int i=0; i<8; i++)
                {
                    word[i] = binaryContent[(int) readChars + i];
                }
                serialPorts[choiceBoxSerialPorts.getSelectionModel().getSelectedIndex()].
                        writeBytes(word, 8);
                readChars += 8;
            }
