### ISSUE TITLE
Can I change data in application by bootloader?

### ISSUE THREAD

**Issue by SalihSalurr** [viktorvano/STM32-Bootloader#5]
Can I change data in application by bootloader? For example, my app have PID and I want to change these value. If I use HAL_Flash I have to erase sector and app maybe be go wrong. I want to change just value not program. I have a idea for that. There are bootloader mode and app mode. Manually writing the required address with pointer in the application to the bootloader and change pointer value. Is there any method without erase sector?

**Comment by pauleffect90** [comment]
yeah.

You can define a linker section as such:


MEMORY
{
FLASH (rx)                 : ORIGIN = 0x08000000, LENGTH = 20K
RAM1 (xrw)                 : ORIGIN = 0x20000014, LENGTH = 0x2FFE6
SEMAPHORE (rw)             : ORIGIN = 0x20000004, LENGTH = 16   <--- this is your non-volatile memory (so to speak)
RAM_SHARED (xrw)           : ORIGIN = 0x20030000, LENGTH = 10K
}

and include it at the end

  .ARM.attributes 0       : { *(.ARM.attributes) }
   MAPPING_TABLE (NOLOAD) : { *(MAPPING_TABLE) } >RAM_SHARED
   MB_MEM1 (NOLOAD)       : { *(MB_MEM1) } >RAM_SHARED
   MB_MEM2 (NOLOAD)       : { _sMB_MEM2 = . ; *(MB_MEM2) ; _eMB_MEM2 = . ; } >RAM_SHARED
   SEMAPHORE (NOLOAD)       : { _sSEMAPHORE = . ; *(SEMAPHORE ) ; _eSEMAPHORE = . ; } >SEMAPHORE
 
finally, include _sSEMAPHORE, _eSEMAPHORE in your startup .s file

.word _sSEMAPHORE
.word _eSEMAPHORE

Thats it.

**Comment by viktorvano** [comment]
When you unlock your flash, you are able to write data.
Just set what data and an address where to write it.
status = HAL_FLASH_Program(FLASH_TYPEPROGRAM_WORD, address, dataToFlash);

There are steps how I write data in "void flashWord(uint32_t dataToFlash)"

void flashWord(uint32_t dataToFlash)
{
	if(flashStatus == Unlocked)
	{
	  volatile HAL_StatusTypeDef status;
	  uint8_t flash_attempt = 0;
	  uint32_t address;
	  do
	  {
		  if(App == App1)
			  address = APP1_START + Flashed_offset;
		  else
			  address = APP2_START + Flashed_offset;
		  status = HAL_FLASH_Program(FLASH_TYPEPROGRAM_WORD, address, dataToFlash);
		  flash_attempt++;
	  }while(status != HAL_OK && flash_attempt < 10 && dataToFlash != readWord(address));
	  if(status != HAL_OK)
	  {
		  CDC_Transmit_FS((uint8_t*)&"Flashing Error!\n", strlen("Flashing Error!\n"));
	  }else
	  {//Word Flash Successful
		  Flashed_offset += 4;
		  CDC_Transmit_FS((uint8_t*)&"Flash: OK\n", strlen("Flash: OK\n"));
	  }
	}else
	{
	  CDC_Transmit_FS((uint8_t*)&"Error: Memory not unlocked nor erased!\n",
			  strlen("Error: Memory not unlocked nor erased!\n"));
	}
}
