### ISSUE TITLE
Not an issue but a question 

### ISSUE THREAD

**Issue by simon88** [viktorvano/STM32-Bootloader#6]
Hi
First if all thanks for your project it’s really usefull. I’m not an expert in  Java and I’d like to know if you can add a documentation to explain how to build jar file. 
thanks

**Comment by viktorvano** [comment]
It is an artifact that should be configured by an IDE that you have. And there are tutorials on each Java IDEs.

Here is a 2 minute tutorial.
https://www.youtube.com/watch?v=_XQjs1xGtaU

**Comment by simon88** [comment]
Nice thanks a lot
